### ISSUE TITLE
Class missing in the CCNode initialize 

### ISSUE THREAD

**Issue by Swatto** [rubymotion-community/Joybox#16]
I discover a problem with the CCNode : it can't access to class of Joybox in the initialize.

I was looking to a proper way to embed entities in my code and I write a player entity class with CCNode as a super class. Easier to have variable with his life, score in that class than in the game logic.

When I try to initialize the class, the sprite creation fails

``` ruby
class PlayerEntity < CCNode
  attr_accessor :sprite
  def initialize
    self.sprite = Joybox::Core::Sprite.new(
      file_name: 'sprites/player.png',
      position: [Screen.half_width, Screen.half_height]
      )
  end
end
```

The solution is to make a different method to construct the properties of it and call that method in the scene

``` ruby
class PlayerEntity < CCNode
  attr_accessor :sprite

  def initSprite
    self.sprite = Sprite.new(
      file_name: 'sprites/player.png',
      position: [Screen.half_width, Screen.half_height]
      )
  end
end

class MenuLayer < Joybox::Core::Layer

  def on_enter
    @player = PlayerEntity.new
    @player.initSprite
    self << @player.sprite
  end

  def on_exit
    # Tear down
  end
end
```

Is it normal ? That's not very handy.

**Comment by Swatto** [comment]
I found the solution. It's a RubyMotion that don't fire the initialize method :

``` ruby
class PlayerEntity < CCNode
  attr_accessor :sprite
  def init
    super
    self.sprite = Sprite.new(
      file_name: 'sprites/player.png',
      position: [Screen.half_width, Screen.half_height]
      )
    self
  end
end
```

I think it could be great to explain that approach for best practice.

**Comment by NSCoder** [comment]
Awesome! Yes the problem is that the objective-c objects use init as initializer, but if you want the full ruby behavior you can do the following:

``` ruby
class NSObject

  def init
    self.send(:initialize)
    self
  end

end
```

I think in the next version we should fix this! Thank you for the feedback!
