### ISSUE TITLE
Undefined method 'postion'

### ISSUE THREAD

**Issue by willrax** [rubymotion-community/Joybox#18]
Hey.

Getting this error when trying to run an app in the simulator:

``` bash
(main)> 2013-05-15 21:48:27.231 square[34838:c07] sprite.rb:19:in `new:': undefined method `position=' for nil:NilClass (NoMethodError)
    from background_layer.rb:4:in `on_enter'
    from layer.rb:23:in `onEnter'
    from node.rb:7:in `<<:'
    from game_scene.rb:3:in `on_enter'
    from scene.rb:10:in `onEnter'
2013-05-15 21:48:27.233 square[34838:c07] *** Terminating app due to uncaught exception 'NoMethodError', reason: 'sprite.rb:19:in `new:': undefined method `position=' for nil:NilClass (NoMethodError)
    from background_layer.rb:4:in `on_enter'
    from layer.rb:23:in `onEnter'
    from node.rb:7:in `<<:'
    from game_scene.rb:3:in `on_enter'
    from scene.rb:10:in `onEnter'
```

Here is the background_layer file.

``` ruby
class BackgroundLayer < Joybox::Core::Layer
  def on_enter
    background = Sprite.new(file_name: "images/background.png",
                            position: [Screen.half_width, Screen.half_height])
    self << background
  end
end
```

Tried all the troubleshooting techniques from the readme but no luck.

Any ideas on what it is?

**Comment by NSCoder** [comment]
Hey Willrax!

The problem seems to be that the 'images/background.png' file is missing, the problem is when you create a new sprite in cocos2d it looks for the image and if it is missing it returns nil. Just check that your image in place, and it will work :)

Let me know :)

JK

**Comment by willrax** [comment]
Ah ok. I have an image in there that is background-hd.png. Do I need both types of image in there?

**Comment by NSCoder** [comment]
You can have the both of them, but the main one is the non retina. background.png

**Comment by willrax** [comment]
Cool. Changing the name from -hd did the trick! :+1:

**Comment by NSCoder** [comment]
Awesome! :D Let me know if i can help you with something else :)
