### ISSUE TITLE
Action does not work with PhysicsSprite.

### ISSUE THREAD

**Issue by yonekawa** [rubymotion-community/Joybox#19]
I want to run rotate action with PhysicsSprite.
However, it does not work.

I think we need this solution. 
http://www.cocos2d-iphone.org/forum/topic/12183

We need world->getBodyList() and body->getUserData().
How about it?

**Comment by NSCoder** [comment]
Hello Yonekawa!

We are working on enabling the actions to run on physics sprites, but we want it to be made automatically: just run the action and done!.

But as well we need more information on the bodies (getBodyList(), getUserData()), it's ok if we implement it for the next release?

**Comment by yonekawa** [comment]
Thank you for your response.
You mean that next Joybox release enables Action with PhysicsSprite, right?

I am looking forward to next version Joybox!

**Comment by NSCoder** [comment]
Yes! We are trying to make the actions compatible with the physics sprites, I believe it will be ready for the next release :)

**Comment by NSCoder** [comment]
Hello Kenichi!

Now we have experimental support on the Physics Sprites, please send us comments about how it works and if it make sense how we implement it :)

Cheers
