### ISSUE TITLE
Events: `on_mouse_entered`, `on_mouse_moved` and `on_mouse_exited` do not fire

### ISSUE THREAD

**Issue by burtlo** [rubymotion-community/Joybox#22]
I am not able to get the `on_mouse_entered`, `on_mouse_moved` and `on_mouse_exited` events to fire within my layer:

``` ruby
class HeroLayer < Joybox::Core::Layer

  def on_enter
    setup_events
  end

  def setup_events
    on_mouse_down do |event, button|
      puts "on_mouse_down #{event} #{button}"
    end

    on_mouse_dragged do |event, button|
      puts "on_mouse_dragged #{event} #{button}"
    end

    on_mouse_up do |event, button|
      puts "on_mouse_up #{event} #{button}"
    end

    on_mouse_scroll do |event, button|
      puts "on_mouse_scroll #{event}"
    end

    on_mouse_entered do |event|
      puts "on_mouse_entered"
    end

    on_mouse_moved do |event|
      puts "on_mouse_moved"
    end

    on_mouse_exited do |event|
      puts "on_mouse_exited"
    end

    on_key_down do |event|
      puts "on_key_down #{event}"
      puts "#{event.keyCode} #{event.characters} #{event.charactersIgnoringModifiers} #{event.modifierFlags}"
    end

    on_key_up do |event|
      puts "on_key_up #{event}"
      puts "#{event.keyCode} #{event.characters} #{event.charactersIgnoringModifiers} #{event.modifierFlags}"
    end

  end

end
```

**Comment by NSCoder** [comment]
Hello Franklin:

Can you please try adding the following in your app_delegate.rb:

``` ruby
@window.setAcceptsMouseMovedEvents(true)
```

I hope it helps!

Thank you!

JK

**Comment by burtlo** [comment]
Independently I started searching for an answer and came across the same suggestion. `on_mouse_moved` now fires, however, `on_mouse_entered` and `on_mouse_exited` still do not fire.

Should I add the small snippet of code to the OSX template?

```
@window.setAcceptsMouseMovedEvents(true)
```

**Comment by NSCoder** [comment]
Hey Franklin:

There was missing a NSTrackingArea for the GLView, thats why the on_mouse_entered and on_mouse_entered were not getting called. I just commit the fix (You can use it if you setup the git repository in the Gemfile).

About the OSX template, I think is better to stick with the Cocos2D defaults keeping the setAcceptsMouseMovedEvents to false.

Also thank you very much for the report! This was difficult to fix!

JK

**Comment by burtlo** [comment]
That's awesome. Thanks for the fix. I'll update the documentation to include those events.

**Comment by NSCoder** [comment]
Awesome! Thank you!
