### ISSUE TITLE
Simulator refuses to start up when font file with ampersand is in the resources

### ISSUE THREAD

**Issue by rkachowski** [rubymotion-community/Joybox#23]
If you add a ttf font file to the resources that has an ampersand in the font name (the font name as specified in the ttf definition, not the filename - although that crashes as well) then the simulator will refuse to install the application.

The following error is produced

> $ rake simulator
>     Build ./build/iPhoneSimulator-6.1-Development
>     Build /Users/donaldhutchison/.rvm/gems/ruby-1.9.3-p327/gems/joybox-1.0.0/vendor/vendor-ios/cocos_2d
>     Build /Users/donaldhutchison/.rvm/gems/ruby-1.9.3-p327/gems/joybox-1.0.0/vendor/vendor-ios/box_2d
>   Compile ./app/scenes/menu_scene.rb
>      Link ./build/iPhoneSimulator-6.1-Development/circle-jerk.app/circle-jerk
>    Create ./build/iPhoneSimulator-6.1-Development/circle-jerk.dSYM
>  Simulate ./build/iPhoneSimulator-6.1-Development/circle-jerk.app
> **\* simulator session started with error: Error Domain=DTiPhoneSimulatorErrorDomain Code=1 "iOS Simulator failed to install the application." UserInfo=0x102001820 {NSLocalizedDescription=iOS Simulator failed to install the application., DTiPhoneSimulatorUnderlyingErrorCodeKey=-1}
> rake aborted!
> Command failed with status (1): [DYLD_FRAMEWORK_PATH="/Applications/Xcode.a...]

Here's a font with that infernal symbol for the sake of testing http://www.dafont.com/c-c-red-alert-inet.font

**Comment by rkachowski** [comment]
my bad, i got a bit over eager when playing around

**Comment by NSCoder** [comment]
Oh! No problem. I try it on a regular RubyMotion project and it happen as well, do you find any solution?

Thanks

JK
