### ISSUE TITLE
Box2D: Accessing additional methods on World and other objects

### ISSUE THREAD

**Issue by burtlo** [rubymotion-community/Joybox#30]
I wanted to access the method `ClearForces` on World. However, it is not available in Joybox. Please tell me if I have figured this out correctly to add this functionality (and other functionality in Box2D).
1. Clone https://github.com/CurveBeryl/Joybox-Box2D
2. Add the method prototype to [B2DWorld.h](https://github.com/CurveBeryl/Joybox-Box2D/blob/master/Box2D/Dynamics/B2DWorld.h)
3. Define the method in [B2DWorld.mm](https://github.com/CurveBeryl/Joybox-Box2D/blob/master/Box2D/Dynamics/B2DWorld.mm)
4. Compile Joybox-Box2D for OSX and iOS
5. Copy the static libraries (.a) to Joybox
6. Redefine the box_2d.bridgesupport for iOS and OSX
7. Define the wrapper methods in [world.rb](https://github.com/rubymotion/Joybox/blob/master/motion/joybox/physics/world.rb).

**Comment by NSCoder** [comment]
Hello Franklin!

Yes is they are the correct steps! If you have any problem, just let me know!

JK

**Comment by NSCoder** [comment]
Closing this bug for now :). Also we add the instructions on the bridge support on the Box2d repository.
