### ISSUE TITLE
Getting undefined method when instantiating a sprite

### ISSUE THREAD

**Issue by jamonholmgren** [rubymotion-community/Joybox#32]
Cross-posted: https://groups.google.com/forum/?fromgroups#!topic/joybox-wrapper/_5B6m8mwAqE

My code:

``` ruby
class StartMenuLayer < Joybox::Core::Layer
  def on_enter
    MenuLabel.default_font_size = 40

    self << start_bg
    self << start_menu
  end

  def start_bg
    @bg ||= begin
      Joybox::Core::Sprite.new(file_name: "CAP-StartBG", position: CGPointMake(0, 0))
    end
  end

  def start_menu
    @menu ||= begin
      start_image = MenuImage.new image_file_name: "CAP-MenuButtonStart" do |menu_item|
        Joybox.director << ReadyScene.new
      end

      Menu.new items: [ start_image ], position: CGPointMake(300, 200)
    end
  end

  def on_exit
    # Perform any state clean if needed
  end
end
```

Error:

```
 sprite.rb:19:in `new:': undefined method `position=' for nil:NilClass (NoMethodError)
    from start_menu_layer.rb:11:in `start_bg'
    from start_menu_layer.rb:5:in `on_enter'
    from layer.rb:23:in `onEnter'
    from node.rb:7:in `<<:'
    from start_scene.rb:4:in `on_enter'
    from scene.rb:10:in `onEnter'
```

Any ideas? Love the framework so far.
- Jamon

**Comment by jamonholmgren** [comment]
Fixed it...wow what a frustrating error! I apparently need to provide the .png (unlike UIImage?) extension. It would be great if there were a more helpful error message.

**Comment by NSCoder** [comment]
I am sorry to read that you have such a trouble, the underlying problem is that cocos returns nil when it does not found the image for the sprite, which is ok for obj-c but it causing a lot of trouble in ruby :(. I think is a great idea, it will include some kind of message for the next release. 

I hope you are still enjoying joybox :)

**Comment by jamonholmgren** [comment]
Ah, got it. Yes, I do like Joybox. It's a lot of work to make a game, especially creating the graphics. :)
