### ISSUE TITLE
Need access to Cocos2d Structs

### ISSUE THREAD

**Issue by freebrevik** [rubymotion-community/Joybox#40]
Currently, Structs found in Cocos2d are inaccessible such as ccTexParams. When previously vendoring cocos2d myself, I would resolve this by editing the bridge support file, and captializing the first two letters making it CCTexParams. This may not be the best solution, as I think the bridge supports are automatically generated and may be overridden.

**Comment by NSCoder** [comment]
Hello!

Of course, let me check what i can do to fix this problem! Anyway thanks for the highlights on how to fix it :)

Thanks

**Comment by freebrevik** [comment]
I noticed you have a bridge support exceptions, I'm not very familiar with this aspect of bridgesupport, are those an extension to the main bridge support file? can CCTexParams (or other structs) be overridden there?

**Comment by NSCoder** [comment]
Yes you can override somethings of the bridgesupport file, but I am not sure it will let you override a Struct name. But its worth the try

**Comment by freebrevik** [comment]
I made a fork of JoyBox to explore this issue, and I was curious, how can I get it to rebuild the cocos2d vendored project

**Comment by freebrevik** [comment]
unfortunately, I wasn't able to get it to work using the method I described above. though it did work for me before when i was vendoring cocos2d myself. I can't really explain why it wouldn't work now. Maybe it has to do with rubymotion > 2.0. You can try it yourself if you like, I might be just doing something wrong, it could be that cocos2d needs to be rebuilt, but I don't think the bridge support files influence the library, I thought they work together with the library to resolve issues. Any other ideas?

**Comment by freebrevik** [comment]
Oddly enough, ccColor4B works, if you say CcColor4B, same with CcBlendFunc.. I don't really see why they would work and others dont... CcColor4F doesn't work for example

**Comment by NSCoder** [comment]
I think we can change manually the names of the cocos2d library, but in the long term it will be like a nightmare because any patch they release we will have to merge it into the project. I am thinking of exploring creating the classes dynamically in obj-c and add them to the cocos2d project.

I am curious what is the error that RM tells you when you change the structs to upper case?

**Comment by NSCoder** [comment]
Oh i forgot, can you help me try the following: NSClassFromString('CCTexParams') to see if it works? I will look into the bridgesupport right now :)

**Comment by freebrevik** [comment]
Changing to uppercase just appears to do nothing for me right now. No errors. I opened up the library to see if there was anything different between ccColor4B, and ccTexParams but I couldn't find anything obvious. ccColor4B is defined as = "{_ccColor4B=CCCC}", and you can make a pointer in ruby to it using Pointer.new("{_ccColor4B=CCCC}") doing the same for ccTexParams which is defined as "{_ccTexParams=IIII}", trying to do that gives you an error that crashes REPL, saying that it couldn't find that description, even though its clearly in the library. ill try the NSClassFromString though. To Test if anything works, grab a texture from any sprite, and try this:

```
p_tex = Pointer.new(CCTexParams.type)
p_tex[0] = CCTexParams.new(GL_LINEAR, GL_LINEAR, GL_REPEAT, GL_REPEAT)

sprite.texture.setTexParameters(p_tex)
```

I tried doing this with a :id pointer, but it got an error saying it expects: "{_ccTexParams=IIII}" (which it apparently also believes doesn't exist)

**Comment by freebrevik** [comment]
Sadly NSClassFromString didn't work, but it did for CcColor4B. I just don't understand why CcColor4B works but CcColor4F doesn't, they are defined exactly the same way in the Types.h... so weird.

**Comment by NSCoder** [comment]
Good news I have been able to make it work changing it from:

``` xml
<struct type='{_ccTexParams=&quot;minFilter&quot;I&quot;magFilter&quot;I&quot;wrapS&quot;I&quot;wrapT&quot;I}' name='ccTexParams'>
```

to:

``` xml
<struct type='{CCTexParams=&quot;minFilter&quot;I&quot;magFilter&quot;I&quot;wrapS&quot;I&quot;wrapT&quot;I}' name='CCTexParams'>
```

Then please remove the .repl_history if it exists and clean the project. Also i think it should not be needed to change this line but just to be sure is this one:

``` xml
<arg type='^{_ccTexParams=IIII}' name='texParams' index='0' declared_type='ccTexParams*'/>
```

to:

``` xml
<arg type='^{CCTexParams=IIII}' name='texParams' index='0' declared_type='ccTexParams*'/>
```

**Comment by freebrevik** [comment]
This isn't working for me. Not sure why, when you say rebuild the project is it enough to rebuild the project im references joybox from? or do I need to go into the joybox folder and rake it too?

**Comment by freebrevik** [comment]
Oh wait, it does, I need to reference it as CcTexParams, instead of CCTexParams. Great! Maybe you should try putting these in the 'exceptions' file and see if it works. That way you don't have to worry about generating new bridgesupport files and them getting overridden

**Comment by NSCoder** [comment]
Awesome! I am glad it works... of course in the next version we will do our best to try to make all of these structs available :)

**Comment by freebrevik** [comment]
I will probably edit in a lot myself, would it help you any if I contribute any my changes when im doing?

**Comment by NSCoder** [comment]
Of course! It will be a awesome if you can send us your bridgesupport when finished!

**Comment by freebrevik** [comment]
This stopped working for me in 2.5, how about for you?

**Comment by NSCoder** [comment]
Which struct is giving you problems? I haven't notice any trouble on the master branch version

**Comment by freebrevik** [comment]
ccTexParams (CCTexParams) again after updating to 2.5 :(

**Comment by NSCoder** [comment]
I just tried with CcTexParams and it worked :/ can you try?

**Comment by freebrevik** [comment]
Is that with the bridgesupport change?

**Comment by freebrevik** [comment]
My problem is with the setTexParams... I can create one but cant pass it

**Comment by NSCoder** [comment]
Oh... I dont know how its implemented in your game, but it seams that it receives a pointer of ccTextParams. In that case you should use a RubyMotion pointer, I think it should be Pointer.new(CcTextParams, 4) but i am not quite sure.

Here is the class reference of Pointer maybe you get it faster: http://www.rubymotion.com/developer-center/api/Pointer.html

**Comment by freebrevik** [comment]
I know, this is how I'm currently doing it, it worked before but after 2.5 it just stopped :(  
    p_tex = Pointer.new(CCTexParams.type)
    p_tex[0] = CCTexParams.new(GL_LINEAR, GL_LINEAR, GL_REPEAT, GL_REPEAT)

```
sprite.texture.setTexParameters(p_tex)
```

It complains its looking for a _ccTexParams, not a CCTexParams.

**Comment by NSCoder** [comment]
Can we try reverting the Bridgesupport and using CcTextParams?

**Comment by freebrevik** [comment]
I'm trying it

**Comment by freebrevik** [comment]
Worked ^^. I guess this issue was fixed, and I was unfixing it, using the old fix lol.

**Comment by NSCoder** [comment]
Hehehe! Well something less to be worried :) Happy that works!

**Comment by freebrevik** [comment]
Any reason you reopened the issue?

**Comment by NSCoder** [comment]
Miss click, sorry

**Comment by spiderSorus** [comment]
Hey, is there a code example using this floating around? I'm trying to use it but everything I try complains uninitialized constant.
