### ISSUE TITLE
Undefined symbols for architecture armv7

### ISSUE THREAD

**Issue by ippan** [rubymotion-community/Joybox#45]
Undefined symbols for architecture armv7

there have no arm 7 in libCocosBuilderReader.a libCocosDenshion.a

so it can't compile to real devices

**Comment by NSCoder** [comment]
Sorry I forgot to recompile the library to update the architectures, now they all have ARM7 & ARM7s

Thank you for the report!

**Comment by NSCoder** [comment]
I will close this one!

Thanks!

**Comment by ippan** [comment]
it works now!!!
thanks^^
