### ISSUE TITLE
Exception when trying to use the tile map

### ISSUE THREAD

**Issue by rkachowski** [rubymotion-community/Joybox#48]
Whenever I try to use the TileMap class in an application I get a crash. With the debugger enabled I get the following message.

```
123 /Users/JuanKaram/Downloads/cocos2d-iphone/cocos2d/CCTMXXMLParser.m: No such file or directory.
Program received signal EXC_ARITHMETIC, Arithmetic exception.
0x0003e6e0 in -[CCTMXTilesetInfo rectForGID:] (self=0xc04e110, _cmd=0x45638f, gid=<value temporarily unavailable, due to optimizations>) at /Users/JuanKaram/Downloads/cocos2d-iphone/cocos2d/CCTMXXMLParser.m:123
    in /Users/JuanKaram/Downloads/cocos2d-iphone/cocos2d/CCTMXXMLParser.m
Current language:  auto; currently objective-c
```

Here's the code I'm using, in case i'm doing something insane..

``` ruby
include Joybox::Core

class MainScene < Joybox::Scene

    def on_enter
        self << TLayer.new
    end
end

class TLayer < Joybox::Layer
    include Joybox::TMX

    def on_enter
        tile_map = TileMap.new file_name: "testmap1.tmx"

        self << tile_map
    end
end
```

This also occurs when I try to use the cocos CCTMXTiledMap class directly.

**Comment by NSCoder** [comment]
Hey Donald!

After reviewing the problem my best guess is that there is something wrong with the map file, can you please send it to me?

If you also want to take a look i will check if the path of the tile image file is correct and exists in the route inside the application resources.

Hope it helps!

**Comment by rkachowski** [comment]
Oh wow, you're totally right, it was the path to the image. Once I change that to be relative to the resources directory it loads fine. I was thrown off by the error message :/

Thanks for your help!
