### ISSUE TITLE
Getting a funky issue with ios7 and xcode 5

### ISSUE THREAD

**Issue by jwaldrip** [rubymotion-community/Joybox#51]
``` sh
rake simulator
     Build ./build/iPhoneSimulator-7.0-Development
     Build /Users/jwaldrip/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/joybox-1.1.1/vendor/vendor-ios/cocos_2d
     Build /Users/jwaldrip/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/joybox-1.1.1/vendor/vendor-ios/cocos_denshion
     Build /Users/jwaldrip/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/joybox-1.1.1/vendor/vendor-ios/cocos_builder_reader
     Build /Users/jwaldrip/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/joybox-1.1.1/vendor/vendor-ios/box_2d
     Build /Users/jwaldrip/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/joybox-1.1.1/vendor/vendor-ios/kazmath
  Simulate ./build/iPhoneSimulator-7.0-Development/Asteroids.app
2013-09-17 22:03:20.647 Asteroids[4403:80b] Cannot find executable for CFBundle 0x9e4f130 </Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/AccessibilityBundles/CertUIFramework.axbundle> (not loaded)
(main)> %
```

**Comment by NSCoder** [comment]
Hey Jason,

It seems a Xcode5 related problem, here are some links:

https://discussions.apple.com/thread/1496640?threadID=1496640
http://stackoverflow.com/questions/2345263/cannot-find-executable-for-cfbundle-cfplugin-error
https://groups.google.com/forum/#!search/Cannot$20find$20executable$20for$20CFBundle$20(not$20loaded)/rubymotion/_tcikfIkPNo/oIp9oCrZzcwJ

It seems a permissions problem, hope it helps.

JK

**Comment by crosebrugh** [comment]
FWIW, after digging through the forums, doing these 2 things worked for me:

1) Disk Utility - repair permissions

2) In the iOS Simulator, choose 'iOS Simulator' > 'Reset Content and Settings...' then quit the sim and rake again

**Comment by Fedos** [comment]
I had the same problem when my Xcode.app was renamed to Xcode 5.app. When I returned it back, everything worked perfectly.

**Comment by NSCoder** [comment]
I believe is related to the xcode-select command :), I'll leave this open for anyone with the same problem

**Comment by chareice** [comment]
Reset

**Comment by ahmetabdi** [comment]
Reset Content and Settings works, I think it's down to opening different apps in the same session. Just needs a wipe

**Comment by harshitgupta** [comment]
@crosebrugh's idea worked perfectly... only reseting the simulator won't help all the time. U might need to repair the disk permissions before you reset it... Thanks buddy...
