### ISSUE TITLE
Provide Box2D.framwork's source code

### ISSUE THREAD

**Issue by yonekawa** [rubymotion-community/Joybox#6]
We need Box2D.framwork's source code to contributing.

For example, I want to porting `b2RevoluteJoint` into Joybox.
However, I can't get(and change) Box2D.framework source in your repository.

**Comment by NSCoder** [comment]
Sorry! I was out the grid for a couple of days... but now I am home :). Here is the URL of the Box2D wrapper: https://github.com/CurveBeryl/Joybox-Box2D

**Comment by yonekawa** [comment]
Thank you very much!!
