### ISSUE TITLE
world.new_body does not work when installed from rubygems

### ISSUE THREAD

**Issue by yonekawa** [rubymotion-community/Joybox#7]
When I installed joybox from rubygems, app crashes with this message at world.new_body.

```
Objective-C stub for message `createBodyInPosition:type:' type `@@:{CGPoint=ff}i' not precompiled. Make sure you properly link with the framework or library that defines this message.
```

When I built joybox on github repository, there is no problem.
I found the difference to repository's one and rubygems's one.

```
 <method selector='createBodyInPosition:type:'>
  - <arg declared_type='id' index='0' type='@' name='position'/>
  - <arg declared_type='B2DBodyTypes' index='1' type='i' name='bodyType'/>
  - <retval declared_type='B2DBody*' type='@'/>
  + <arg name='position' index='0' type='{CGPoint=ff}' declared_type='CGPoint'/>
  + <arg name='bodyType' index='1' type='i' declared_type='B2DBodyTypes'/>
  + <retval type='@' declared_type='B2DBody*'/>
 </method>
```

Could you update rubygem's one?

**Comment by NSCoder** [comment]
Thanks for the report!

It's quite strange but i have the same file in the repo and bundle, actually is the changed one:

``` XML
<method selector='createBodyInPosition:type:'>
<arg name='position' index='0' type='{CGPoint=ff}' declared_type='CGPoint'/>
<arg name='bodyType' index='1' type='i' declared_type='B2DBodyTypes'/>
<retval type='@' declared_type='B2DBody*'/>
</method>
```

And is more strange because that suppose to be working and the following not:

``` XML
<arg declared_type='id' index='0' type='@' name='position'/>
<arg declared_type='B2DBodyTypes' index='1' type='i' name='bodyType'/>
<retval declared_type='B2DBody*' type='@'/>
```

Can you help me running this on your machine, to see if this fixes it?

1.- Delete .repl_history file
2.- rake clean
3.- gem uninstall -a joybox
4.- gem install joybox
5.- rake

**Comment by yonekawa** [comment]
Thank you for your reply!
However, It doesn't fixed this error

```
Objective-C stub for message `createBodyInPosition:type:' type `@@:{CGPoint=ff}i' not precompiled. Make sure you properly link with the framework or library that defines this message.
```

**Comment by yonekawa** [comment]
> I found the difference to repository's one and rubygems's one.

Sorry, this is my misconception.
createBodyInPosition:type: definition is same.
However, file has a difference.

**Comment by yonekawa** [comment]
I tried to replace Box2D.framework.bridgesupport by repository's one.

```
cp REPOSITORY/vendor/Box2D.framework/Box2D.framework.bridgesupport ~/.rbenv/versions/1.9.3-p385/gemsets/motion/gems/joybox-0.0.5/vendor/Box2D.framework/
```

It works!
strange...:(

**Comment by NSCoder** [comment]
Oh! Can you get me the difference?

Can you give me some more information, just to understand what can be wrong?
1. If you download the lastest version of the repo, it also crashes?
2. Is your RubyMotion version up to date?
3. Do you see a vendor folder on your app?
4. Is any chance that you can send me your app just for checking?

Thanks!

**Comment by yonekawa** [comment]
> 1. If you download the lastest version of the repo, it also crashes?

It works. I tried to replace bridgesupport file from repo into gems. https://github.com/rubymotion/Joybox/issues/7#issuecomment-16453723

> 1. Is your RubyMotion version up to date?

```
motion -v     
1.35
```

> 1. Do you see a vendor folder on your app?

No. my project does not have vendor/ now.

> 1. Is any chance that you can send me your app just for checking?

Yes! I will send the project source code.

**Comment by yonekawa** [comment]
This is the difference gem and repo
https://gist.github.com/yonekawa/5397305

This is my (fail) project
https://github.com/yonekawa/catapult-defence

**Comment by NSCoder** [comment]
When you replace the .bridgesupport file, for it to take effect: you need also to remove the .repl_file and do a rake clean. 

I will stay tuned for the code so I can see what's the root of the problem ;)

Thank you!

**Comment by yonekawa** [comment]
I tried 2 install flow.
I found that this is problem from Bundler.

1.- Delete .repl_history file
2.- rake clean
3.- gem uninstall -a joybox
4.- bundle install
5.- rake

-> app crash

1.- Delete .repl_history file
2.- rake clean
3.- gem uninstall -a joybox
4.- gem install joybox
5.- rake

-> no problem

**Comment by NSCoder** [comment]
Oh really strange! Great that is working now! 

I will close it for the moment, if it happens again i will reopen it and look further into this.

Thank You! \o/
